#include <iostream>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <fstream>
#include <string>
#include <cstring>
#include <vector>
#include <stdio.h>
#define PATH "/assignments/sypass/data"
using namespace std;